fix: github CI

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,22 +2,38 @@
 
 set -euo pipefail
 
-source "$(dirname "$0")/../lib/utils.sh"
+die() {
+  local message=$1
+  echo "$message" >&2
+  exit 1
+}
+
+git_address() {
+  echo 'https://github.com/GothenburgBitFactory/taskwarrior.git'
+}
+
+git_clone() {
+  local version=$1
+  local path=$2
+
+  if git --version &> /dev/null; then
+    git clone "$(git_address)" -b "v$version" "$path"
+  else
+    die "'git' required."
+  fi
+}
 
 git_download() {
   local version=$1
   local path=$2
   local install_type=$3
-  local url_git="https://rakudo.org/dl/rakudo"
 
   if [ "$install_type" != "version" ]; then
     die "Install type '$install_type' not supported."
   fi
 
   echo "Downloading version $version to ${path}/tw ..."
-  git_clone $version "${path}/tw"
-
-  if [ "$?" -eq 0 ]; then
+  if git_clone "$version" "${path}/tw"; then
     echo "Download complete!"
   else
     die "Checksum verification failure."
diff --git a/bin/latest-stable b/bin/latest-stable
--- a/bin/latest-stable
+++ b/bin/latest-stable
@@ -2,6 +2,31 @@
 
 set -euo pipefail
 
-source "$(dirname "$0")/../lib/utils.sh"
+die() {
+  local message=$1
+  echo "$message" >&2
+  exit 1
+}
+
+git_get_tags() {
+  local url=$1
+  if git --version &> /dev/null; then
+    git ls-remote --tags "$url"
+  else
+    die "'git' required."
+  fi
+}
+
+git_address() {
+  echo 'https://github.com/GothenburgBitFactory/taskwarrior.git'
+}
+
+get_available_releases() {
+  git_get_tags "$(git_address)" |
+    grep -v '{}$' |
+    grep 'refs/tags/v' |
+    cut -d/ -f3 |
+    cut --delimiter v -f2
+}
 
 get_available_releases | tail -1
